config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/messages', to: 'messages#index'
  get '/messages/new', to:'messages#new'
  post 'messages', to:'messages#create'
  resources :messages do
    get 'invoke_llm', on: :collection
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
require 'net/http'

class MessagesController < ApplicationController
    skip_before_action :verify_authenticity_token
    def invoke_llm
        puts "invoke_llm is called" # Debug statement
        @response = send_test_request
        # ... other code for this action
      end
    def index 
        puts "In index"
        @messages = Message.all 
        @new_message = Message.new
      end
    def new
        @message = Message.new
    end
    def create 
        @message = Message.new(message_params) 
        if @message.save 
          redirect_to '/messages' 
        else 
          render :index
        end 
    end 
    private 
    def message_params 
        params.require(:message).permit(:content) 
    end
    
    
      private
    
      def send_test_request
        puts "send test is called" # Debug statement
        uri = URI('http://localhost:1234/v1/chat/completions')
        http = Net::HTTP.new(uri.host, uri.port)
        headers = { 'Content-Type' => 'application/json' }
        request_body = {
          messages: [
            { role: 'system', content: 'Always answer in rhymes.' },
            { role: 'user', content: 'Introduce yourself.' }
          ],
          temperature: 0.7,
          max_tokens: -1,
          stream: false
        }
    
        request = Net::HTTP::Post.new(uri, headers)
        request.body = request_body.to_json
    
        response = http.request(request)
        response.body
      rescue => e
        e.message
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDevAsst</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Interface</title>
</head>
<main>
  <div class="chat-window">
    <div class="messages">
      <% @messages.each do |message| %>
        <div class="message">
          <p><%= message.content %></p>
          <span class="timestamp"><%= message.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
        </div>
      <% end %>
    </div>

    <div class="input-area">
      <%= form_for Message.new do |form| %>
      <%= form.label :message %><br> 
        <%= form.text_area :content, placeholder: "Type your message here..." %>
        <%= form.submit "Send" %>
      <% end %>
<%= link_to 'LLM!', invoke_llm_messages_path %>
    </div>
  </div>
</main>

app/views/messages/invoke_llm.html.erb
<h1>API Response</h1>

<div>
  <p>Response from API:</p>
  <pre><%= @response %></pre>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Interface</title>
</head>
<body>
    <header>
        <nav>
            <div class="logo">My Developer Assistant</div>
        </nav>
    </header>
    
    <main>
        <div class="chat-window">
            <div class="messages">
                <!-- Messages will be displayed here -->
            </div>
            <div class="input-area">
                <input type="text" id="userInput" placeholder="Type your message here...">
                <%= link_to 'Send', "messages" ,  class: "button"%> 
            </div>
        </div>
    </main>

    <footer>
        <p>© 2023 My Developer Assistant</p>
    </footer>
</body>
</html>